### PR TITLE
Docker build and run support added

### PR DESCRIPTION
**Pull request by tsukhu**
The angular2 spring boot integration is good , but very cumbersome without docker support. Changes have been added to enable Docker support via docker compose and maven plugin docker .

### CODE REVIEW

**Comment by kucharzyk** [comment]
It looks great. Thanks.

I'll review it later (after work) and  merge.

btw: next time please create pull request to dev branch

**Comment by kucharzyk** [comment]
I'm sorry but I can't merge this PR.

Docker is great but removing "eureka.instance.hostname" property will break existing functionallity and it won't work without docker. 

I'll move your changes to dev branch and try to make it works with and without docker.

**Comment by kucharzyk** [comment]
I've just recreated your configuration on dev branch.

I'll try to create dedicated profiles for docker and standalone configurations

**Comment by tsukhu** [comment]
I tried out the dev branch build and run (using Docker) .. it works perfectly :+1: 
One addition that can be done is to have spring-boot admin added as well

**Comment by tsukhu** [comment]
One more suggestion .. we could potentially have only one copy of wait-for-service.sh (since they are identical) and copy it from a common parent location to all docker builds

**Pull request closed without merging**
