### PR TITLE
support for spring-boot admin

### PR DESCRIPTION
**Pull request by tsukhu**
Spring boot admin feature added . This has been tested on the docker container build. There is one issue though .. the API and AUTH seem to always appear offline in spring boot admin ui. I am not sure about the reason for that (may be related to security or do we need to enable the actuator for these ??

Any way take a look at this.

### CODE REVIEW

**Comment by kucharzyk** [comment]
Api and auth services are running on custom context paths (/api and /auth). It can be the reason. I'll check it

**Comment by kucharzyk** [comment]
I've fixed it.

It was both of them. First spring admin get 404 because of custom contextPath and after changing path to / Spring security started to block this route.

Now it works, but for production usage actuator endpoints should be secured (by application or by some rules on apache at front of app)

**Comment by tsukhu** [comment]
The spring boot admin server needs to have specific health monitors available only for authenticated users .. like what is done here https://github.com/joshiste/spring-boot-admin-samples

**Comment by kucharzyk** [comment]
I'll try to secure monitors at the weekend. But at first I will migrate app to angular rc.5 and new alpha of material. There are lots of changes

**Comment by tsukhu** [comment]
That may require upgrading webpack to v2 as there were issues with webpack  v1 and angular rc5. The AngularClass has created a new angular2-starter for that ..

**Comment by kucharzyk** [comment]
We already have webpack2 on dev branch

**Pull request merged**
